title: Harsh Singhvi # your name (or website title) here
logo: "/images/6CB15605-E17B-435C-98A9-66451678E61C.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="left" >
  <br><br>
  <a href="https://instagram.com/insomniac_coder?igshid=1m2jur72ucxhf"><img src="/images/6CB15605-E17B-435C-98A9-66451678E61C.jpeg" alt ="LOGO" style="float:right;width:45%;height:45%;" ></a>
  <br><br>
  <a href="https://twitter.com/harshsinghvi29?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @harshsinghvi29</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  <br><br>
  This website in under construction.
  <br><br>
  By the time you can contact me though:-
  <br><br>
  <a href="http://linkedin.com/in/harsh-singhvi-658968a1">View My LinkedIn Profile</a>   
  <br>
  <a href="https://instagram.com/insomniac_coder?igshid=1m2jur72ucxhf">View My Instagram Profile</a> 
    <a href="https://drive.google.com/file/d/113fKyscCjzslVrqtyBUsM-87e9hajSuM/view?usp=drivesdk">MDM</a> 

  </p>

plugins: ['jekyll-twitter-plugin']
theme: jekyll-theme-midnight
google_analytics: UA-141565153-1 # your Google Analytics tracking ID here
